# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SendBird-iOS' do
  use_frameworks!

  pod 'AffdexSDK-iOS'
  pod 'Appsee'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'PhoneNumberKit'
  pod 'SwiftyBeaver'
  
  pod 'SendBirdSDK'
  pod 'AlamofireImage'
  pod 'MGSwipeTableCell'
  pod 'FLAnimatedImage'
  pod 'NYTPhotoViewer'
#  pod 'HTMLKit', '~> 2.0'
  pod 'TTTAttributedLabel'
  pod 'RSKImageCropper'
end

swift4Targets = ['PhoneNumberKit']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if (target.name == 'AWSCore') || (target.name == 'AWSKinesis')
      puts target.name
      target.build_configurations.each do |config|
        config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
      end
    end
    swift_version = '3.2'
    if swift4Targets.include?(target.name)
      swift_version = '4.0'
    end
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = swift_version
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end